"""Account management utilities.

The Python-only PlayerAccount layer has been removed.  Characters now own
their passwords directly, mirroring ROM src/merc.h PCData.pwd.
"""

from .account_manager import load_character, save_character
from .account_service import (
    CreationSelection,
    account_exists,
    character_exists,
    create_account,
    create_character,
    create_character_record,
    clear_active_accounts,
    get_creation_classes,
    get_creation_races,
    get_hometown_choices,
    get_weapon_choices,
    get_race_archetype,
    is_account_active,
    is_valid_account_name,
    is_valid_character_name,
    login_character,
    lookup_creation_class,
    lookup_creation_race,
    lookup_hometown,
    lookup_weapon_choice,
    LoginFailureReason,
    LoginResult,
    list_characters,
    login,
    login_with_host,
    roll_creation_stats,
    finalize_creation_stats,
    sanitize_account_name,
    release_account,
    release_character,
)

__all__ = [
    "load_character",
    "save_character",
    "account_exists",
    "character_exists",
    "create_account",
    "create_character",
    "create_character_record",
    "login",
    "login_character",
    "login_with_host",
    "list_characters",
    "CreationSelection",
    "get_creation_races",
    "lookup_creation_race",
    "get_race_archetype",
    "get_creation_classes",
    "lookup_creation_class",
    "get_hometown_choices",
    "lookup_hometown",
    "get_weapon_choices",
    "lookup_weapon_choice",
    "roll_creation_stats",
    "finalize_creation_stats",
    "is_valid_account_name",
    "is_valid_character_name",
    "sanitize_account_name",
    "clear_active_accounts",
    "is_account_active",
    "release_account",
    "release_character",
    "LoginFailureReason",
    "LoginResult",
]
