"""One-shot data fix: inject missing ``resets`` arrays into ``data/areas/*.json``.

The area-JSON converter at ``mud/scripts/convert_are_to_json.py`` already emits a
``resets`` array, but the checked-in JSON files were generated by an earlier
revision and never regenerated. Production boots from JSON, so the world is
empty of mobs (the in-game arena report that surfaced this bug).

This script only injects ``resets`` (and only when missing). All other fields
in the existing JSON — including hand-edited ROM-parity fixes like
``midgaard.json:room 3001 → up exit → key: 0`` and the JSONLD-018
``ROOM_NO_MOB`` removal — are preserved untouched.
"""
from __future__ import annotations

import json
from pathlib import Path

from mud.scripts.convert_are_to_json import convert_area

REPO_ROOT = Path(__file__).resolve().parent.parent
ARE_DIR = REPO_ROOT / "area"
JSON_DIR = REPO_ROOT / "data" / "areas"


def patch_one(json_path: Path) -> tuple[bool, str]:
    """Return (changed, message) for one JSON file."""
    data = json.loads(json_path.read_text())
    if "resets" in data and data["resets"]:
        return False, "already has resets"

    are_path = ARE_DIR / (json_path.stem + ".are")
    if not are_path.exists():
        return False, f"no matching .are at {are_path}"

    converted = convert_area(str(are_path))
    resets = converted.get("resets", [])
    if not resets:
        return False, ".are produced no resets"

    data["resets"] = resets
    json_path.write_text(json.dumps(data, indent=2) + "\n")
    return True, f"injected {len(resets)} resets"


def main() -> None:
    changed = 0
    skipped = 0
    for json_path in sorted(JSON_DIR.glob("*.json")):
        ok, msg = patch_one(json_path)
        if ok:
            changed += 1
            print(f"[fix] {json_path.name}: {msg}")
        else:
            skipped += 1
            print(f"[skip] {json_path.name}: {msg}")
    print(f"\nDone. {changed} files patched, {skipped} skipped.")


if __name__ == "__main__":
    main()
