"""ROM title table and helpers.

ROM Reference: src/const.c:421-721 (title_table)
"""

from __future__ import annotations

from mud.models.constants import MAX_LEVEL, Sex

TITLE_TABLE: tuple[tuple[tuple[str, str], ...], ...] = (
    (
        ("Man", "Woman"),
        ("Apprentice of Magic", "Apprentice of Magic"),
        ("Spell Student", "Spell Student"),
        ("Scholar of Magic", "Scholar of Magic"),
        ("Delver in Spells", "Delveress in Spells"),
        ("Medium of Magic", "Medium of Magic"),
        ("Scribe of Magic", "Scribess of Magic"),
        ("Seer", "Seeress"),
        ("Sage", "Sage"),
        ("Illusionist", "Illusionist"),
        ("Abjurer", "Abjuress"),
        ("Invoker", "Invoker"),
        ("Enchanter", "Enchantress"),
        ("Conjurer", "Conjuress"),
        ("Magician", "Witch"),
        ("Creator", "Creator"),
        ("Savant", "Savant"),
        ("Magus", "Craftess"),
        ("Wizard", "Wizard"),
        ("Warlock", "War Witch"),
        ("Sorcerer", "Sorceress"),
        ("Elder Sorcerer", "Elder Sorceress"),
        ("Grand Sorcerer", "Grand Sorceress"),
        ("Great Sorcerer", "Great Sorceress"),
        ("Golem Maker", "Golem Maker"),
        ("Greater Golem Maker", "Greater Golem Maker"),
        ("Maker of Stones", "Maker of Stones"),
        ("Maker of Potions", "Maker of Potions"),
        ("Maker of Scrolls", "Maker of Scrolls"),
        ("Maker of Wands", "Maker of Wands"),
        ("Maker of Staves", "Maker of Staves"),
        ("Demon Summoner", "Demon Summoner"),
        ("Greater Demon Summoner", "Greater Demon Summoner"),
        ("Dragon Charmer", "Dragon Charmer"),
        ("Greater Dragon Charmer", "Greater Dragon Charmer"),
        ("Master of all Magic", "Master of all Magic"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Master Mage", "Master Mage"),
        ("Mage Hero", "Mage Heroine"),
        ("Avatar of Magic", "Avatar of Magic"),
        ("Angel of Magic", "Angel of Magic"),
        ("Demigod of Magic", "Demigoddess of Magic"),
        ("Immortal of Magic", "Immortal of Magic"),
        ("God of Magic", "Goddess of Magic"),
        ("Deity of Magic", "Deity of Magic"),
        ("Supremity of Magic", "Supremity of Magic"),
        ("Creator", "Creator"),
        ("Implementor", "Implementress"),
    ),
    (
        ("Man", "Woman"),
        ("Believer", "Believer"),
        ("Attendant", "Attendant"),
        ("Acolyte", "Acolyte"),
        ("Novice", "Novice"),
        ("Missionary", "Missionary"),
        ("Adept", "Adept"),
        ("Deacon", "Deaconess"),
        ("Vicar", "Vicaress"),
        ("Priest", "Priestess"),
        ("Minister", "Lady Minister"),
        ("Canon", "Canon"),
        ("Levite", "Levitess"),
        ("Curate", "Curess"),
        ("Monk", "Nun"),
        ("Healer", "Healess"),
        ("Chaplain", "Chaplain"),
        ("Expositor", "Expositress"),
        ("Bishop", "Bishop"),
        ("Arch Bishop", "Arch Lady of the Church"),
        ("Patriarch", "Matriarch"),
        ("Elder Patriarch", "Elder Matriarch"),
        ("Grand Patriarch", "Grand Matriarch"),
        ("Great Patriarch", "Great Matriarch"),
        ("Demon Killer", "Demon Killer"),
        ("Greater Demon Killer", "Greater Demon Killer"),
        ("Cardinal of the Sea", "Cardinal of the Sea"),
        ("Cardinal of the Earth", "Cardinal of the Earth"),
        ("Cardinal of the Air", "Cardinal of the Air"),
        ("Cardinal of the Ether", "Cardinal of the Ether"),
        ("Cardinal of the Heavens", "Cardinal of the Heavens"),
        ("Avatar of an Immortal", "Avatar of an Immortal"),
        ("Avatar of a Deity", "Avatar of a Deity"),
        ("Avatar of a Supremity", "Avatar of a Supremity"),
        ("Avatar of an Implementor", "Avatar of an Implementor"),
        ("Master of all Divinity", "Mistress of all Divinity"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Master Cleric", "Master Cleric"),
        ("Holy Hero", "Holy Heroine"),
        ("Holy Avatar", "Holy Avatar"),
        ("Angel", "Angel"),
        ("Demigod", "Demigoddess"),
        ("Immortal", "Immortal"),
        ("God", "Goddess"),
        ("Deity", "Deity"),
        ("Supreme Master", "Supreme Mistress"),
        ("Creator", "Creator"),
        ("Implementor", "Implementress"),
    ),
    (
        ("Man", "Woman"),
        ("Pilferer", "Pilferess"),
        ("Footpad", "Footpad"),
        ("Filcher", "Filcheress"),
        ("Pick-Pocket", "Pick-Pocket"),
        ("Sneak", "Sneak"),
        ("Pincher", "Pincheress"),
        ("Cut-Purse", "Cut-Purse"),
        ("Snatcher", "Snatcheress"),
        ("Sharper", "Sharpress"),
        ("Rogue", "Rogue"),
        ("Robber", "Robber"),
        ("Magsman", "Magswoman"),
        ("Highwayman", "Highwaywoman"),
        ("Burglar", "Burglaress"),
        ("Thief", "Thief"),
        ("Knifer", "Knifer"),
        ("Quick-Blade", "Quick-Blade"),
        ("Killer", "Murderess"),
        ("Brigand", "Brigand"),
        ("Cut-Throat", "Cut-Throat"),
        ("Spy", "Spy"),
        ("Grand Spy", "Grand Spy"),
        ("Master Spy", "Master Spy"),
        ("Assassin", "Assassin"),
        ("Greater Assassin", "Greater Assassin"),
        ("Master of Vision", "Mistress of Vision"),
        ("Master of Hearing", "Mistress of Hearing"),
        ("Master of Smell", "Mistress of Smell"),
        ("Master of Taste", "Mistress of Taste"),
        ("Master of Touch", "Mistress of Touch"),
        ("Crime Lord", "Crime Mistress"),
        ("Infamous Crime Lord", "Infamous Crime Mistress"),
        ("Greater Crime Lord", "Greater Crime Mistress"),
        ("Master Crime Lord", "Master Crime Mistress"),
        ("Godfather", "Godmother"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Master Thief", "Master Thief"),
        ("Assassin Hero", "Assassin Heroine"),
        ("Avatar of Death", "Avatar of Death"),
        ("Angel of Death", "Angel of Death"),
        ("Demigod of Assassins", "Demigoddess of Assassins"),
        ("Immortal Assasin", "Immortal Assassin"),
        ("God of Assassins", "God of Assassins"),
        ("Deity of Assassins", "Deity of Assassins"),
        ("Supreme Master", "Supreme Mistress"),
        ("Creator", "Creator"),
        ("Implementor", "Implementress"),
    ),
    (
        ("Man", "Woman"),
        ("Swordpupil", "Swordpupil"),
        ("Recruit", "Recruit"),
        ("Sentry", "Sentress"),
        ("Fighter", "Fighter"),
        ("Soldier", "Soldier"),
        ("Warrior", "Warrior"),
        ("Veteran", "Veteran"),
        ("Swordsman", "Swordswoman"),
        ("Fencer", "Fenceress"),
        ("Combatant", "Combatess"),
        ("Hero", "Heroine"),
        ("Myrmidon", "Myrmidon"),
        ("Swashbuckler", "Swashbuckleress"),
        ("Mercenary", "Mercenaress"),
        ("Swordmaster", "Swordmistress"),
        ("Lieutenant", "Lieutenant"),
        ("Champion", "Lady Champion"),
        ("Dragoon", "Lady Dragoon"),
        ("Cavalier", "Lady Cavalier"),
        ("Knight", "Lady Knight"),
        ("Grand Knight", "Grand Knight"),
        ("Master Knight", "Master Knight"),
        ("Paladin", "Paladin"),
        ("Grand Paladin", "Grand Paladin"),
        ("Demon Slayer", "Demon Slayer"),
        ("Greater Demon Slayer", "Greater Demon Slayer"),
        ("Dragon Slayer", "Dragon Slayer"),
        ("Greater Dragon Slayer", "Greater Dragon Slayer"),
        ("Underlord", "Underlord"),
        ("Overlord", "Overlord"),
        ("Baron of Thunder", "Baroness of Thunder"),
        ("Baron of Storms", "Baroness of Storms"),
        ("Baron of Tornadoes", "Baroness of Tornadoes"),
        ("Baron of Hurricanes", "Baroness of Hurricanes"),
        ("Baron of Meteors", "Baroness of Meteors"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Master Warrior", "Master Warrior"),
        ("Knight Hero", "Knight Heroine"),
        ("Avatar of War", "Avatar of War"),
        ("Angel of War", "Angel of War"),
        ("Demigod of War", "Demigoddess of War"),
        ("Immortal Warlord", "Immortal Warlord"),
        ("God of War", "God of War"),
        ("Deity of War", "Deity of War"),
        ("Supreme Master of War", "Supreme Mistress of War"),
        ("Creator", "Creator"),
        ("Implementor", "Implementress"),
    ),
)


def format_title_storage(title: str) -> str:
    """Mirror ROM set_title() storage semantics from src/act_info.c:2520-2543."""

    if title and title[0] not in (".", ",", "!", "?"):
        return " " + title
    return title


def default_title_name(class_index: int, level: int, sex: Sex | int) -> str:
    """Return the ROM class title string for the given class, level, and sex."""

    safe_class = min(max(int(class_index), 0), len(TITLE_TABLE) - 1)
    safe_level = min(max(int(level), 0), MAX_LEVEL)
    sex_index = 1 if int(sex) == int(Sex.FEMALE) else 0
    return TITLE_TABLE[safe_class][safe_level][sex_index]


def default_title_text(class_index: int, level: int, sex: Sex | int) -> str:
    """Return the ROM default title text before set_title() spacing."""

    return f"the {default_title_name(class_index, level, sex)}"


def default_title_storage(class_index: int, level: int, sex: Sex | int) -> str:
    """Return the persisted/runtime title string as stored on pcdata.title."""

    return format_title_storage(default_title_text(class_index, level, sex))
