name: Tests

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,test]
      - name: Lint with ruff (if available)
        run: |
          # Check if ruff is available and run it
          if command -v ruff &> /dev/null; then
            ruff check .
          else
            echo "Ruff not available, skipping linting"
          fi
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest --tb=short --timeout=30
        timeout-minutes: 10
